; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Catálogo PDF"
#define MyAppVersion "1.0.1.0"
#define MyAppPublisher "Simpletrade"
#define MyAppExeName "catalog_app.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{81CEFA67-0A38-4AD8-B4C3-D5BBA23DF3FF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\Jose\Documents\GitHub\catalog_app\Empaquetado\InstaladorCompilado
OutputBaseFilename=CatalogoPdfSetup
SetupIconFile=C:\Users\Jose\Documents\GitHub\catalog_app\Empaquetado\logoST.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Jose\Documents\GitHub\catalog_app\Empaquetado\redist\*"; DestDir: {tmp}
Source: "C:\Users\Jose\Documents\GitHub\catalog_app\Empaquetado\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jose\Documents\GitHub\catalog_app\Empaquetado\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jose\Documents\GitHub\catalog_app\Empaquetado\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{tmp}\VC_redist.x64.exe"; Parameters: "/q /norestart"; \
    Check: (not Is64BitInstallMode) and VC2019RedistNeedsInstall('x64'); \
    Flags: waituntilterminated; \
    StatusMsg: "Installing VC++ 2019 redistributables..."
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function VC2019RedistNeedsInstall(Arch: string): Boolean;
var 
  Version: String;
begin
  Result := True;
  if Arch = 'x64' then
  begin
    if RegKeyExists( HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{CB4A0FDE-1126-4AE2-97C6-A243692C3D95}') then
    begin
      Log('VC Redist Version check : found ');
      Result := False;
    end;
  end;
 end;
